version: '3.7'

services:
  db:
      image: mongo
      container_name: mongodb
      restart: always
      environment:
         MONGO_INITDB_ROOT_USERNAME: adm
         MONGO_INITDB_ROOT_PASSWORD: 1234
         MONGO_INITDB_DATABASE: mongodb
      volumes:
      - mongo_data:/data/mongo
      ports:
         - 27017:27017

  app:
      image: python
      container_name: pythonContainer
      build: .
      command: ["python" ,"src/main.py"]
      command: tail -f /dev/null
      ports:
        - 5000:5000
      depends_on:
        - db
      volumes:
        - .:/app


volumes:
  mongo_data:
    driver: local
