name: main_CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Checking Python 3.8.10
      uses: actions/setup-python@v4
      with:
        python-version: 3.8.10
    
    - name: Installing poetry
      run: |
        python3 -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Installing dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install requirements.txt

    - name: Running docker commands
        run: docker-compose up --force-recreate


  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Checking Python 3.8.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.8.10'

    - name: Installing python3 dependencies
      run: |
        pip install whatlies==0.7.0
        pip install pyyaml
        python3 -m pip install --upgrade pip
        pip install flake8 pytest-cov

    - name: Testing with Pytest
      run: |
        pytest --cov
      
    - name: Lint with flake8
      run: |
        flake8 --extend-ignore=E302,E101,E131,W191,W293,W292,W291 --count --select=E9,F63,F7,F82 --exclude=*.pyc,*migrations* --show-source --statistics
        flake8 --extend-ignore=E302,E101,E131,W191,W293,W292,W291 --count --max-complexity=10 --max-line-length=226 --exclude=*.pyc,*migrations* --statistics 

  #deploy:
