name: main_CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Checking Python 3.8.10
      uses: actions/setup-python@v4
      with:
        python-version: 3.8.10
    
    - name: Installing poetry
      run: |
        python3 -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Installing dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install requirements.txt

    - name: Running docker commands
      run: docker-compose up --force-recreate

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Checking Python 3.8.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.8.10'        

    - name: Testing with Pytest
      run: |
        python3 -m pip install --upgrade pip
        pip install pytest
        pytest --cov
      
    - name: Clean code using Lint with flake8
      run: |
        python3 -m pip install --upgrade pip
        pip install flake8 pytest-cov
        pip install flake8
        flake8 ./src
      continue-on-error: true
       

  # deploy:
    
